didx-xyz/yoma

- src/api/src/application/Yoma.Core.Api/Controllers/OrganizationController.cs
- src/api/src/domain/Yoma.Core.Domain/Core/Helpers/HttpContextAccessorHelper.cs
- src/api/src/domain/Yoma.Core.Domain/Entity/Services/OrganizationService.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Interfaces/IOpportunityBackgroundService.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/OpportunityBackgroundService.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/OpportunityService.cs
> Resolve Dotnet Format

- src/web/youth/tailwind.config.ts
* It breaks CI Linting (prettier)
> Disable DaisyUI Logging

- .husky/pre-push
* Don't `git fetch` in pre-push hook
* Add prettier to pre-push
> Update pre-push git hook

- .github/workflows/continuous-integration.yml
Cherry pick of #131, #132, #133, and #134
> Update Github Actions

- .github/workflows/continuous-integration.yml
- src/api/docker-compose.yml
Until https://github.com/adorsys/keycloak-config-cli/issues/927 is resolved
> Pin Keycloak to `22.0.3`

- src/api/src/domain/Yoma.Core.Domain/Entity/Services/UserProfileService.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Models/MyOpportunitySearchFilterAdmin.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Models/MyOpportunitySearchFilterBase.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Services/MyOpportunityService.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Validators/MyOpportunitySearchFilterValidator.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/OpportunityInfoService.cs
Admin and user search now supports a list of VerificationStatuses
> Admin search now supports filtering on a list of organizations

- src/api/src/application/Yoma.Core.Api/Controllers/MyOpportunityController.cs
- src/api/src/domain/Yoma.Core.Domain/Lookups/Services/SkillService.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Extensions/MyOpportunityExtensions.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Interfaces/IMyOpportunityService.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Models/MyOpportunity.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Models/MyOpportunityInfo.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Models/MyOpportunitySearchCriteriaOpportunity.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Services/MyOpportunityService.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/MyOpportunity/Repositories/MyOpportunityRepository.cs
Added api/v3/myOpportunity/search/filter/opportunity enpoint to return a list of opportunities as verification search criteria
> Added user photo details to model

- src/api/src/application/Yoma.Core.Api/Controllers/MyOpportunityController.cs
- src/api/src/application/Yoma.Core.Api/Controllers/OpportunityController.cs
- src/api/src/application/Yoma.Core.Api/Controllers/SSIController.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Interfaces/IOpportunityInfoService.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/OpportunityInfoService.cs
Added {id}/admin/info to get the opportunity info as admin
> search/admin now returns OpportunityInfo

- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Services/MyOpportunityService.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Extensions/OpportunityExtensions.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Models/OpportunityInfo.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/OpportunityInfoService.cs
Added status to OpportunityInfo
> Resolved missing orderBy claus with MyOpportunity search

- src/api/cicd/scripts/sqlserver-init/post.sql
- src/api/src/domain/Yoma.Core.Domain/SSI/Services/SSIBackgroundService.cs
- src/api/src/domain/Yoma.Core.Domain/Startup.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.AriesCloud/Client/AriesCloudClient.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.AriesCloud/Yoma.Core.Infrastructure.AriesCloud.csproj
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/MyOpportunity/Repositories/MyOpportunityRepository.cs
Debugged and activated tenant creation
> Fixed post.sql

- src/api/src/application/Yoma.Core.Api/Controllers/SSIController.cs
- src/api/src/domain/Yoma.Core.Domain/SSI/Models/SSICredentialInfo.cs
- src/api/src/domain/Yoma.Core.Domain/SSI/Services/Lookups/SSISchemaEntityService.cs
- src/api/src/domain/Yoma.Core.Domain/SSI/Services/SSIWalletService.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.AriesCloud/Client/AriesCloudClient.cs
Added TODO's
Ordered additional attributes by NameDisplay
ListSchemaEntities endpoint now requires a schemaType
> Attributes now hidden with search

- src/api/src/domain/Yoma.Core.Domain/LaborMarketProvider/Models/Skill.cs
- src/api/src/domain/Yoma.Core.Domain/SSI/Services/SSIWalletService.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Emsi/Client/EmsiClient.cs
SSIWalletService.Search: Order by DateIssue clientside pending wql documentation
> EMSI ListSkills: Returns a temporary list due to provider being offline

- src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/Migrations/20231113082340_ApplicationDb_Initial_Seeding.cs
Will only take effect with the next deployment with a clean db start
> Renamed provider type "Task" to "Impact"

- src/web/src/api/models/organisation.ts
- src/web/src/components/Global.tsx
- src/web/src/pages/opportunities/[[...query]]/index.tsx
- src/web/src/pages/organisations/[[...query]]/index.tsx
- src/web/src/pages/organisations/[id]/edit.tsx
- src/web/src/pages/organisations/[id]/index.tsx
- src/web/src/pages/organisations/[id]/info.tsx
- src/web/src/pages/organisations/[id]/opportunities/[[...query]]/index.tsx
- src/web/src/pages/organisations/[id]/opportunities/[opportunityId]/index.tsx
- src/web/src/pages/organisations/[id]/opportunities/[opportunityId]/info.tsx
- src/web/src/pages/organisations/[id]/verifications/[[...query]]/index.tsx
- src/web/src/pages/organisations/register/index.tsx
- src/web/src/server/auth.ts
> profile switching improvements 

- src/api/src/application/Yoma.Core.Api/Startup.cs
- src/api/src/application/Yoma.Core.Api/appsettings.json
- src/api/src/domain/Yoma.Core.Domain/Core/Models/AppSettings.cs
- src/api/src/domain/Yoma.Core.Domain/Core/Models/AppSettingsDatabaseRetryPolicy.cs
- src/api/src/domain/Yoma.Core.Domain/Marketplace/Services/MarketPlaceService.cs
- src/api/src/domain/Yoma.Core.Domain/Startup.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/Startup.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Zlto/Client/ZltoClient.cs
> Added configurable DatabaseRetryPolicy

- src/api/src/application/Yoma.Core.Api/Startup.cs
- src/api/src/application/Yoma.Core.Api/appsettings.json
- src/api/src/domain/Yoma.Core.Domain/Core/Interfaces/IExecutionStrategyService.cs
- src/api/src/domain/Yoma.Core.Domain/Core/Models/AppSettings.cs
- src/api/src/domain/Yoma.Core.Domain/Core/Models/AppSettingsDatabaseRetryPolicy.cs
- src/api/src/domain/Yoma.Core.Domain/Core/Services/BlobService.cs
- src/api/src/domain/Yoma.Core.Domain/Entity/Services/OrganizationService.cs
- src/api/src/domain/Yoma.Core.Domain/Entity/Services/UserProfileService.cs
- src/api/src/domain/Yoma.Core.Domain/Entity/Services/UserService.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Services/MyOpportunityService.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/OpportunityService.cs
- src/api/src/domain/Yoma.Core.Domain/Reward/Services/RewardBackgroundService.cs
- src/api/src/domain/Yoma.Core.Domain/Reward/Services/WalletService.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.AriesCloud/Services/ExecutionStrategyService.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.AriesCloud/Startup.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/Core/Services/ExecutionStrategyService.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/Startup.cs
Added ExecutionStrategy helper service
All user transactions now executed under the context execution strategy
> Reintroduced DB retry policy

- .mise.toml
- .rtx.toml
- README.md
* [Coming from rtx](https://mise.jdx.dev/rtx.html)
> Rename `rtx` to `mise`

- .github/dependabot.yml
* https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates#nuget-cli
> Add NuGet to Dependabot

- helm/yoma-api/conf/base/secrets.yaml
- helm/yoma-api/conf/dev/secrets.yaml
- src/api/src/application/Yoma.Core.Api/Attributes/ApiKeyAttribute.cs
- src/api/src/application/Yoma.Core.Api/Controllers/ExternalPartnerController.cs
- src/api/src/application/Yoma.Core.Api/appsettings.json
- src/api/src/domain/Yoma.Core.Domain/Entity/Validators/OrganizationRequestValidatorBase.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.AriesCloud/Client/AriesCloudClient.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.AriesCloud/Client/AriesCloudClientFactory.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.AriesCloud/Extensions/RolesExtension.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.AriesCloud/Extensions/SchemaExtensions.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.AriesCloud/Interfaces/ISSEListenerService.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.AriesCloud/Services/SSEListenerService.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.AriesCloud/Yoma.Core.Infrastructure.AriesCloud.csproj
Refactored AriesCloud infrastratuce
Tested tenant creation and credentials issuance
> Updated Aries SDK

- helm/yoma-api/conf/base/secrets.yaml
- helm/yoma-api/conf/dev/secrets.yaml
- src/api/src/application/Yoma.Core.Api/appsettings.json
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Services/MyOpportunityService.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.AriesCloud/Yoma.Core.Infrastructure.AriesCloud.csproj
My Opportunity completion validation now defaults to the end of the day for date completed
> Enabled AriesCloudApi SDK tenant token cache

- src/web/src/components/Opportunity/OpportunityCompletionRead.tsx
- src/web/src/components/SearchInput.tsx
- src/web/src/pages/organisations/[id]/opportunities/[opportunityId]/info.tsx
- src/web/src/pages/organisations/[id]/verifications/[[...query]]/index.tsx
- Page UI Styling
- Result Models
- Fix breadcrumb artifact
- Seacrh input heightOverride
> Partner Verification UI:

- src/web/src/components/Organisation/Detail/VerifyOverview.tsx
- src/web/src/components/Organisation/LogoTitle.tsx
- src/web/src/pages/organisations/[id]/verify.tsx
- src/web/tailwind.config.ts
> Org approval UI:

- src/web/src/api/models/opportunity.ts
- src/web/src/components/Opportunity/OpportunityFilterHorizontal.tsx
- src/web/src/components/Opportunity/OpportunityPublicSmall.tsx
- src/web/src/pages/opportunities/[[...query]]/index.tsx
- src/web/src/pages/opportunities/[opportunityId]/index.tsx
- src/web/src/pages/organisations/[id]/opportunities/[[...query]]/index.tsx
- src/web/src/pages/organisations/[id]/opportunities/[opportunityId]/index.tsx
- src/web/src/pages/organisations/[id]/opportunities/[opportunityId]/info.tsx
- src/web/src/pages/organisations/[id]/verifications/[[...query]]/index.tsx
Add filter to check if the opportunity has started or not for Youth
> Add filter to check if the opportunity has started or not for Youth

- src/web/src/components/Global.tsx
- src/web/src/components/NavBar/UserMenu.tsx
- src/web/src/pages/organisations/[[...query]]/index.tsx
- fixed duplicate no rows message on /organisations page
- fixed issue with limited functionality badge not refreshing when switching between active/inactive organisations
- show user menu view for organisations page
- changed inactive to pending on user menu orgs
> general fixes

- helm/keycloak/conf/dev/secrets.yaml
- helm/keycloak/conf/stage/secrets.yaml
- helm/keycloak/values.yaml
- src/api/cicd/scripts/keycloak/users.sh
- src/api/docker-compose.yml
* Add a `system@yoma.world` user based on the Org Admin User
> Yoma System User

- helm/yoma-web/conf/base/secrets.yaml
- helm/yoma-web/conf/base/values.yaml
- helm/yoma-web/conf/dev/secrets.yaml
- helm/yoma-web/conf/dev/values.yaml
Makes it easier to maintain stuff 🤷‍♂️
> Move non-sensitive out of secrets

- src/web/src/components/NavBar/Navbar.tsx
- src/web/src/components/Opportunity/OpportunityFilterHorizontal.tsx
- src/web/src/components/Opportunity/OpportunityFilterVertical.tsx
- src/web/src/components/Opportunity/OpportunityPublicSmall.tsx
- src/web/src/components/Opportunity/OpportunityRow.tsx
- src/web/src/components/PageBackground.tsx
- src/web/src/pages/admin/opportunities/[[...query]]/index.tsx
- src/web/src/pages/opportunities/[[...query]]/index.tsx
- src/web/src/pages/opportunities/[opportunityId]/index.tsx
- src/web/tailwind.config.ts
* Remove jobs from nav
* Move world map down
* Change wolrdwide text on filterbar to country
* Remove autoscroll from youth opp view
* Filterbar domain being filtered instead of items
* Filterbar wrapping & styling
* Opps badges styling
* Remove don't show this from go to op modal
* Change filter text to badges
> Opportunity Filterbar & Goodies:

- src/web/src/api/services/myOpportunities.ts
- src/web/src/components/Opportunity/OpportunityCompletionRead.tsx
- src/web/src/components/Opportunity/OpportunityFilterHorizontal.tsx
- src/web/src/components/Opportunity/OpportunityFilterVertical.tsx
- src/web/src/components/Opportunity/OpportunityPublicSmall.tsx
- src/web/src/components/SearchInputLarge.tsx
- src/web/src/pages/opportunities/[[...query]]/index.tsx
- src/web/src/pages/opportunities/[opportunityId]/index.tsx
* Vertical filter mobile only
* Style vertical filter
* Change filter buttons
* Fix Org logo on Opp Cards
* Saved/Unsaved button feedback
* Save/Remove Opp API endpoints
* Fix large icon on Opp Verification
> Opportunity Filterbar & extras

- helm/yoma-api/conf/dev/values.yaml
- src/api/src/application/Yoma.Core.Api/Startup.cs
* If `replicaCount >= 2` then Hangfire Antiforgery breaks
* HangfireIO/Hangfire#1248
> Ignore Antiforgery Token

- helm/yoma-api/conf/dev/secrets.yaml
- helm/yoma-api/conf/stage/secrets.yaml
* `IMemoryCache` + `replicaCount >= 2` causes issues
* Long term solution is external cache (e.g: Redis)
> Disable Aries CloudAPI Caching

- src/web/src/components/AvatarImage.tsx
- src/web/src/components/NavBar/Navbar.tsx
- src/web/src/components/NavBar/UserMenu.tsx
- src/web/src/components/Organisation/Upsert/AvatarUpload.tsx
- src/web/src/pages/organisations/[[...query]]/index.tsx
- src/web/src/pages/yoid/settings/index.tsx
- Hide Schemas & Connections from admin nav
- Change default icon for avatar
- Fix react-avatar-editor build-issue
- Add avatar image component to UserMenu
- Admin org view avatar images
> Admin nav items

- src/web/src/components/AvatarImage.tsx
- src/web/src/components/Layout/Marketplace.tsx
- src/web/src/components/Opportunity/OpportunityFilterHorizontal.tsx
- src/web/src/components/Opportunity/OpportunityPublicSmall.tsx
- src/web/src/components/Organisation/Upsert/AvatarUpload.module.css
- src/web/src/components/Organisation/Upsert/AvatarUpload.tsx
- src/web/src/components/Organisation/Upsert/OrgAdminsEdit.tsx
- src/web/src/components/Organisation/Upsert/OrgInfoEdit.tsx
- src/web/src/components/Organisation/Upsert/OrgRolesEdit.tsx
- src/web/src/components/PaginationButtons.tsx
- src/web/src/components/SearchInput.tsx
- src/web/src/components/SearchInputLarge.tsx
- src/web/src/pages/admin/opportunities/[[...query]]/index.tsx
- src/web/src/pages/opportunities/[opportunityId]/index.tsx
- src/web/src/pages/organisations/[id]/info.tsx
- src/web/src/pages/organisations/[id]/opportunities/[opportunityId]/info.tsx
- src/web/src/pages/yoid/credentials/[[...query]].tsx
- src/web/src/pages/yoid/settings/index.tsx
- src/web/src/styles/globals.scss
- src/web/tailwind.config.ts
* Align all badges
* Round all buttons
* Horizontal filterbar button styling
* ODV text & country badges
* Marketplace header style
* Update avatar-upload
* Things 'n stuff
> Badges & Buttons

- helm/yoma-api/conf/base/secrets.yaml
- helm/yoma-api/conf/dev/secrets.yaml
- helm/yoma-api/conf/stage/secrets.yaml
* Add the missing SendGrid Templates
* Move SendGrid Templates to the `base` secrets file
> Add missing SendGrid Templates

- .github/workflows/continuous-integration.yml
- helm/keycloak/values.yaml
- helm/yoma-api/values.yaml
* Dotnet `2.48.0` -> `2.49.0`
* Java `1.31.0` -> `1.31.2`
> Bump Datadog Libs

- src/web/src/components/Organisation/LogoTitle.tsx
- src/web/src/components/Organisation/Upsert/OrgAdminsEdit.tsx
- src/web/src/components/Organisation/Upsert/OrgInfoEdit.tsx
- src/web/src/components/Organisation/Upsert/OrgRolesEdit.tsx
- src/web/src/pages/organisations/[id]/edit.tsx
- src/web/src/pages/organisations/[id]/opportunities/[opportunityId]/index.tsx
- src/web/src/pages/organisations/[id]/opportunities/[opportunityId]/info.tsx
* Modal Org edit on Opp Expired
* General styling
* Align form font sizes and padding
* Org edit mobile dropdown
> Org & Opp Edit UI

- src/api/src/domain/Yoma.Core.Domain/Opportunity/Extensions/OpportunityExtensions.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Models/OpportunityInfo.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/OpportunityInfoService.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Validators/OpportunityRequestValidatorBase.cs
Added YomaInfoURL reflecting the URL to the Yoma opportunity info page (environment based)
> Opportunity URL is now optional

- src/api/src/application/Yoma.Core.Api/Controllers/KeycloakController.cs
- src/api/src/domain/Yoma.Core.Domain/Entity/Services/UserProfileService.cs
- src/api/src/domain/Yoma.Core.Domain/IdentityProvider/Interfaces/IIdentityProviderClient.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Keycloak/Client/KeycloakClient.cs
Modified ReceiveKeyCloakEvent method to accept request as JObject for flexibility in handling various request types
> Added logging to include the raw payload in ReceiveKeyCloakEvent method

- src/web/src/pages/opportunities/[opportunityId]/index.tsx
- src/web/src/pages/organisations/[id]/opportunities/[opportunityId]/index.tsx
> Enable opportunities without URLs

- helm/yoma-api/conf/stage/secrets.yaml
Indentation for Yoma API Logging config was off.
Fixed it.
> Fix indentation of API Logging Config

- src/keycloak/themes/yoma/login/resources/css/styles.css
- src/web/src/components/Global.tsx
- src/web/src/components/SearchInput.tsx
- src/web/src/pages/organisations/[id]/opportunities/[[...query]]/index.tsx
- src/web/src/pages/organisations/[id]/opportunities/[opportunityId]/info.tsx
- src/web/src/pages/yoid/settings/index.tsx
Partner Opportunities UI
* Tabbed View
* Styling
* Mobile styling
* Opp Info minor styling
* Disable yoid settings email update
* KC locale dropdown icon
* Yoid Onboarding Modal text
> Partner opps page UI

- src/web/public/scripts/help-scout.js
- src/web/src/pages/_document.tsx
Add Help scout & Gleac-bot scripts
> Add Help scout & Gleac-bot

- src/api/migration/v2-to-v3.sql
- src/api/src/domain/Yoma.Core.Domain/Core/Helpers/DateTimeHelper.cs
- src/api/src/domain/Yoma.Core.Domain/Reward/Models/WalletVoucher.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Zlto/Client/ZltoClient.cs
Migration: Ensure UCT and start / end of date where applicable Added "Opportunity"."MyOpportunity" start and end date data fixes
> Wallet Voucher model now includes a dates tamp

- src/web/src/components/Global.tsx
- src/web/src/components/Layout/YoIDTabbed.tsx
- src/web/src/components/MyOpportunity/OpportunityListItem.tsx
- src/web/src/pages/_document.tsx
- src/web/src/pages/organisations/[id]/opportunities/[[...query]]/index.tsx
- src/web/src/pages/organisations/[id]/opportunities/[opportunityId]/index.tsx
- src/web/src/pages/yoid/credentials/[[...query]].tsx
- src/web/src/pages/yoid/opportunities/completed/[[...query]].tsx
- src/web/src/pages/yoid/opportunities/declined/[[...query]].tsx
- src/web/src/pages/yoid/opportunities/saved/[[...query]].tsx
- src/web/src/pages/yoid/opportunities/submitted/[[...query]].tsx
- src/web/src/pages/yoid/skills/[[...query]].tsx
* Yoid onboarding close button and feedback
* Yoid styling
* Yoid pages empty state mobile
* Yoid Declined Comment
* Yoid stamp background
* Partner Opp view button border
* Partner Opp view Delete tab
* Partner Opp view tab spacing
* Remove GLEAC
> YOID Touchups:

- .github/workflows/continuous-integration.yml
* Or if it was a manual workflow trigger
> Only run e2e if API, Web, or Keycloak had updates

- src/api/src/domain/Yoma.Core.Domain/Opportunity/Validators/OpportunityRequestValidatorBase.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Zlto/Client/ZltoClient.cs
Store item count now uses the store_item_count return on the item category / grouping model
> ZLTO amount is now limited to 2000 on opportunity creation / updating

- src/web/src/components/Carousel/SelectedSnapDisplay.tsx
- src/web/src/components/Marketplace/StoreItemsCarousel.tsx
- src/web/src/components/Opportunity/OpportunitiesCarousel.tsx
- src/web/src/components/Opportunity/OpportunityPublicSmall.tsx
- src/web/src/components/PaginationButtons.tsx
- src/web/src/components/SearchInputLarge.tsx
- src/web/src/pages/marketplace/[country]/index.tsx
- src/web/src/pages/opportunities/[[...query]]/index.tsx
- src/web/src/styles/embla.css
* Mobile card and carousel styling
* Fix search input width
* Dropdown/Icon z-index fix
* Search input button brightness
* Carousel counter to LHS & scaling
> Opps & marketplace cards mobile

- src/web/src/components/Status/MarketplaceDown.tsx
Center text on marketplace down banner
> Center text on marketplace down banner

- src/web/src/components/Opportunity/OpportunityPublicSmall.tsx
Decrease height of Opp card title
> Decrease height of Opp card title

- src/api/Dockerfile
* Clean up comments in Dockerfile
* To calm down Sentry/ASP.NET make an empty `wwwroot` dir
> Empty `wwwroot`

- helm/yoma-api/Chart.yaml
- helm/yoma-api/values.yaml
- helm/yoma-web/Chart.yaml
- helm/yoma-web/templates/deployment.yaml
- helm/yoma-web/values.yaml
- helmfile.yaml
* Make Chart App version more accurate
* Add Datadog APM injection to Yoma Web
> Datadog JS APM injection in Yoma Web

- src/api/src/domain/Yoma.Core.Domain/Entity/Services/OrganizationService.cs
- src/api/src/domain/Yoma.Core.Domain/Entity/Services/UserService.cs
> Fixed issue with new blob objects and not initializing the storage type and key used later to retrieve the URL

- src/web/src/api/services/organizationDashboard.ts
- src/web/src/components/NoRowsMessage.tsx
- src/web/src/components/Organisation/Dashboard/LineChart.tsx
- src/web/src/components/Organisation/Dashboard/OrganisationRowFilter.tsx
- src/web/src/components/Organisation/Dashboard/SkillsChart.tsx
- src/web/src/pages/organisations/[id]/index.tsx
* Hide date filter
* Hide Opps unpublished containers
* Fix select height overflow
* AreaChart padding top
* Small tweaks
* Average conversion message
* Swop dashed lines Viewed/Completed
> Dashboard tweaks

- src/web/src/components/AvatarImage.tsx
- src/web/src/components/Opportunity/OpportunityFilterHorizontal.tsx
- src/web/src/pages/admin/opportunities/[[...query]]/index.tsx
* Redo mobile card styling
* Fix Search bar overflow bug
* Fix filter card shadow cut-off
* Avatar default image size/padding
> Admin Opps Mobile Cards

- src/api/src/domain/Yoma.Core.Domain/Analytics/Services/AnalyticsService.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Services/MyOpportunityService.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Validators/MyOpportunityRequestValidatorVerifyFinalize.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Interfaces/IOpportunityService.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Models/OpportunityAllocateRewardResponse.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/OpportunityService.cs
Ensure comment does not exceed 400 characters in validator
> Append reward pool depletion info to verification comment for 'my' opportunity

- src/api/src/application/Yoma.Core.Api/appsettings.json
- src/api/src/domain/Yoma.Core.Domain/Entity/Services/UserService.cs
- src/api/src/domain/Yoma.Core.Domain/Marketplace/Services/MarketPlaceService.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Services/MyOpportunityService.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Models/OpportunitySearchFilterCriteria.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/OpportunityInfoService.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/OpportunityService.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Validators/OpportunitySearchFilterCriteriaValidator.cs
- src/api/src/infrastructure/Yoam.Core.Infrastructure.Bitly/Client/BitlyClient.cs
- src/api/src/infrastructure/Yoam.Core.Infrastructure.Bitly/Models/BitLinksRequest.cs
- src/api/src/infrastructure/Yoam.Core.Infrastructure.Bitly/Models/BitLinksResponse.cs
- src/api/src/infrastructure/Yoam.Core.Infrastructure.Bitly/Models/BitlyOptions.cs
Disabled (removed) email 'Opportunity_Verification_Pending_Admin'
> Added optional opportunities filter criteria to 'OpportunitySearchFilterCriteria'

- helm/keycloak/conf/dev/values.yaml
- helm/keycloak/conf/local/values.yaml
- helm/keycloak/conf/stage/values.yaml
- helm/keycloak/values.yaml
- helm/yoma-api/conf/dev/secrets.yaml
- helm/yoma-api/conf/dev/values.yaml
- helm/yoma-api/conf/stage/secrets.yaml
- helm/yoma-api/conf/stage/values.yaml
- helm/yoma-web/conf/base/secrets.yaml
- helm/yoma-web/conf/base/values.yaml
- helm/yoma-web/conf/dev/secrets.yaml
- helm/yoma-web/conf/dev/values.yaml
- helm/yoma-web/conf/stage/secrets.yaml
- helm/yoma-web/conf/stage/values.yaml
- helm/yoma-web/values.yaml
Also migrate Yoma Web to `(dev|stage).yoma.world` and drop `v3app`
> [Dev/Stage] Migrate Keycloak from `auth.` subdomain to `/auth`

- src/web/src/components/Global.tsx
- src/web/src/server/auth.ts
* removed toast message when signing in with SSO
* comment & console message clean-up
> remove SSO sign-in message

- src/keycloak/exports/01-yoma-realm.yaml
* `no-reply@yoma.africa` -> `no-reply@yoma.world`
> Fix Keycloak SMTP Sender

- .github/workflows/cicd.yml
* Bump Tailscale `1.62.1` -> `1.64.0`
* Bump Helm `3.14.3` -> `3.14.4`
> Scope Deploy Concurrency by Environment

- src/web/src/components/Carousel/ArrowButtons.tsx
- src/web/src/components/Carousel/SelectedSnapDisplay.tsx
- src/web/src/components/Opportunity/OpportunitiesCarousel.tsx
- src/web/src/components/Opportunity/OpportunityPublicSmall.tsx
- src/web/src/pages/opportunities/[[...query]]/index.tsx
- src/web/src/pages/opportunities/[opportunityId]/index.tsx
- src/web/src/pages/organisations/[[...query]]/index.tsx
- src/web/src/styles/globals.scss
- src/web/tailwind.config.ts
* Organisation admin view tab mobile styling
* Opportunity carousel styling
* Nprogress loader styling
* Update status text
* Cancel submission modal overflow fix
* Custom bounce ease to tailwind config
* Carousel scroll bug fix
Closes YOMA-74, YOMA-75, YOMA-76, YOMA-61, YOMA-54
> Opp Carousel Touchups & Goodies

- src/api/src/domain/Yoma.Core.Domain/ActionLink/Services/LinkService.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/OpportunityService.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/ActionLink/Entities/Link.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/Migrations/20240425123152_ApplicationDb_ActionLink_Name.Designer.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/Migrations/20240425123152_ApplicationDb_ActionLink_Name.cs
> [YOMA-66] Ensure unique names per entity for links that supports multiple links per action

- src/web/src/components/Organisation/OrganisationCardComponent.tsx
- src/web/src/components/Status/ApiErrors.tsx
- src/web/src/pages/_app.tsx
- src/web/src/pages/_document.tsx
- src/web/src/pages/organisations/[id]/index.tsx
- src/web/src/pages/organisations/[id]/opportunities/[opportunityId]/index.tsx
- src/web/src/pages/organisations/[id]/verifications/[[...query]]/index.tsx
- src/web/src/styles/globals.scss
* YOMA-63 ZLTO pools comms tooltip
* YOMA-64 Add org admin name to org dashboard
* YOMA-96 Gleac script
* YOMA-98 Style toasts
* Org card component mobile icon size
Closes YOMA-63, YOMA-64, YOMA-96, YOMA-98
> Gleac modal and UI touchups:

- helm/yoma-api/conf/base/secrets.yaml
- src/api/src/application/Yoma.Core.Api/Controllers/OpportunityController.cs
- src/api/src/application/Yoma.Core.Api/Controllers/OrganizationController.cs
- src/api/src/application/Yoma.Core.Api/Controllers/UserController.cs
- src/api/src/application/Yoma.Core.Api/appsettings.json
- src/api/src/domain/Yoma.Core.Domain/ActionLink/Interfaces/ILinkServiceBackgroundService.cs
- src/api/src/domain/Yoma.Core.Domain/ActionLink/Models/Link.cs
- src/api/src/domain/Yoma.Core.Domain/ActionLink/Services/LinkService.cs
- src/api/src/domain/Yoma.Core.Domain/ActionLink/Services/LinkServiceBackgroundService.cs
- src/api/src/domain/Yoma.Core.Domain/Core/Models/ScheduleJobOptions.cs
- src/api/src/domain/Yoma.Core.Domain/EmailProvider/Enumerations.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Models/MyOpportunityRequestVerify.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Models/MyOpportunityRequestVerifyFinalize.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Services/MyOpportunityService.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Validators/MyOpportunityRequestValidatorVerify.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Extensions/OpportunityExtensions.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Interfaces/IOpportunityInfoService.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Interfaces/IOpportunityService.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/OpportunityInfoService.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/OpportunityService.cs
- src/api/src/domain/Yoma.Core.Domain/Startup.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/ActionLink/Repositories/LinkRepository.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/Startup.cs
- Endpoint get the published or expired opportunity by instant-very link id (Anonymous)
- Endpoint get the instant-verify link by id. Optionally include a QR code (Admin or Organization Admin) My opportunity instant verify implementation
- Link expiration background service
- Link distribution emailer template hookup
- Link repository now supports batching
- Minor refactoring's
> [YOMA-52] Action Links - Instant Verify

- src/web/src/styles/globals.scss
Unhide Gleac chat widget on desktop
> Unhide Gleac chat widget on desktop

- src/web/src/api/models/organisation.ts
- src/web/src/api/models/organizationDashboard.ts
- src/web/src/api/services/organizationDashboard.ts
- src/web/src/components/Opportunity/OpportunityPublicSmall.tsx
- src/web/src/components/Opportunity/Share.tsx
- src/web/src/components/Organisation/OrganisationCardComponent.tsx
- src/web/src/components/Organisation/Upsert/OrgAdminsEdit.tsx
- src/web/src/pages/_app.tsx
- src/web/src/pages/opportunities/[opportunityId]/index.tsx
- src/web/src/pages/organisations/[id]/edit.tsx
- src/web/src/pages/organisations/[id]/index.tsx
- src/web/src/pages/organisations/register/index.tsx
- src/web/src/styles/globals.scss
* Share modal styling
* Toasts desktop position
* Org roles warnimg styling
* Opp card overflow bug fix
* Badges overflow
* Hide Gleac on mobile
* Add inputs for Sso inbound/outbound client ids to org create/edit screens
* Add Sso Inbound/Outbound login counts to Org Dashboard
Closes YOMA-106, YOMA-109
> Style share modal

- helm/yoma-api/conf/base/secrets.yaml
- src/api/src/application/Yoma.Core.Api/appsettings.json
- src/api/src/domain/Yoma.Core.Domain/ActionLink/Services/LinkService.cs
- src/api/src/domain/Yoma.Core.Domain/EmailProvider/Enumerations.cs
- src/api/src/domain/Yoma.Core.Domain/EmailProvider/Models/EmailActionLinkVerify.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Models/Opportunity.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Models/OpportunitySearchFilterCriteria.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/OpportunityService.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/Opportunity/Repositories/OpportunityRepository.cs
Link service internal refactoring
With opportunity search filter criteria, added ability to filter on Published and / or VerificationMethod
> Hooked up the ActionLink_Verify_Created email

- helm/yoma-api/conf/base/secrets.yaml
* Also Disable Sendgrid in Stage
> Update Opportunity Expiration Notification Interval

- helm/keycloak/conf/stage/values.yaml
Atingi has a new pre-prod environment with new URLs
> Update Atingi Pre-Prod URLs

- docker-compose.yml
- helm/keycloak/conf/dev/values.yaml
- helm/keycloak/conf/local/values.yaml
- helm/keycloak/conf/stage/values.yaml
- src/api/docker-compose.yml
- src/web/docker-compose.yml
* Remove the `version` field in Docker Compose files
* Update Atingi Pre-Prod URLs in Compose, Local, and Dev
> Docker Compose `version` is deprecated

- src/keycloak/themes/yoma/login/login-update-password.ftl
- src/keycloak/themes/yoma/login/login.ftl
- src/keycloak/themes/yoma/login/resources/css/styles.css
- src/web/src/components/Opportunity/OpportunityPublicSmall.tsx
- src/web/src/pages/organisations/[id]/verifications/[[...query]]/index.tsx
* Password visibility icon on missing auth pages
* Style bulk verification results
* Fix opportunity cards overflowing
Closes YOMA-171, YOMA-169, YOMA-116, YOMA-177
> Auth screen password icon & opp:

- src/api/src/domain/Yoma.Core.Domain/Opportunity/Validators/OpportunityRequestValidatorBase.cs
Applies to opportunity create and update
> Add validation rule to ensure ParticipantLimit is null when VerificationEnabled is false 

- src/web/src/pages/_document.tsx
> Comment out GLEAC script

- helm/yoma-web/conf/dev/values.yaml
- helm/yoma-web/conf/prod/values.yaml
- helm/yoma-web/conf/stage/values.yaml
> Increase Nginx Buffer sizes

- src/api/cicd/scripts/postgressql-init/post.sql
Opportunity date end not set based on the commitment interval
Participant count only set provided verification enabled 
Credential issuance enabled only set provided verification enabled
> [YOMA-219] Test data script update

- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Services/MyOpportunityService.cs
Added ZltoRewardPool condition
> [YOMA-226] Refactor pending verifications check

- helm/yoma-api/conf/stage/secrets.yaml
- helm/yoma-api/conf/stage/values.yaml
- src/keycloak/exports/01-yoma-realm.yaml
> Vercel related config for staging

- src/api/src/application/Yoma.Core.Api/Controllers/MyOpportunityController.cs
- src/api/src/application/Yoma.Core.Api/Controllers/OpportunityController.cs
- src/api/src/domain/Yoma.Core.Domain/Lookups/Services/TimeIntervalService.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Interfaces/IMyOpportunityService.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Models/MyOpportunityInfo.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Services/MyOpportunityService.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Interfaces/IOpportunityInfoService.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/OpportunityInfoService.cs
Updated endpoint route for opportunity search export to csv
Added endpoint to export verification search to csv
> [YOMA-232] CSV Export

- src/api/src/domain/Yoma.Core.Domain/Analytics/Models/OrganizationSSO.cs
- src/api/src/domain/Yoma.Core.Domain/Analytics/Services/AnalyticsService.cs
Supports graphs and return logins as weekly distinct login counts with a legend and total count
> [YOMA-251] SSO Analytics

- src/web/src/api/models/organizationDashboard.ts
- src/web/src/components/Opportunity/OpportunitiesCarousel.tsx
- src/web/src/components/Organisation/Dashboard/SsoChart.tsx
- src/web/src/components/Organisation/Upsert/OrgAdminsEdit.tsx
- src/web/src/pages/organisations/[id]/edit.tsx
- src/web/src/pages/organisations/[id]/index.tsx
- src/web/src/pages/organisations/[id]/opportunities/[opportunityId]/index.tsx
- src/web/src/pages/organisations/[id]/verifications/[[...query]]/index.tsx
* Create chart for Org Dashboard Sso analytics
* Fix Opp card pagination on mobile
* Select input height on Org Edit
* Verification page warning message
* Opportunity creation/edit warning styling
Closes YOMA-145, YOMA-207, YOMA-208, YOMA-215
> SSO Charts & Opp cards mobile:

- src/web/src/components/Organisation/Dashboard/SsoChart.tsx
> Increase Sso chart size

- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/OpportunityService.cs
- Country: Worldwide, followed by the user's country if authenticated provided country has opportunities, and then countries by opportunity counts descending
- Language: By opportunity counts descending
- Providers: By opportunity counts descending
> [YOMA-294] Opportunity Youth Search Criteria Ordering

- src/api/src/domain/Yoma.Core.Domain/ActionLink/Services/Lookups/LinkStatusService.cs
- src/api/src/domain/Yoma.Core.Domain/Analytics/Services/AnalyticsService.cs
- src/api/src/domain/Yoma.Core.Domain/Core/Helpers/CacheHelper.cs
- src/api/src/domain/Yoma.Core.Domain/Entity/Services/Lookups/OrganizationProviderTypeService.cs
- src/api/src/domain/Yoma.Core.Domain/Entity/Services/Lookups/OrganizationStatusService.cs
- src/api/src/domain/Yoma.Core.Domain/Lookups/Services/CountryService.cs
- src/api/src/domain/Yoma.Core.Domain/Lookups/Services/EducationService.cs
- src/api/src/domain/Yoma.Core.Domain/Lookups/Services/EngagementTypeService.cs
- src/api/src/domain/Yoma.Core.Domain/Lookups/Services/GenderService.cs
- src/api/src/domain/Yoma.Core.Domain/Lookups/Services/LanguageService.cs
- src/api/src/domain/Yoma.Core.Domain/Lookups/Services/TimeIntervalService.cs
- src/api/src/domain/Yoma.Core.Domain/Marketplace/Services/Lookups/TransactionStatusService.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Services/Lookups/MyOpportunityActionService.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Services/Lookups/MyOpportunityVerificationStatusService.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/Lookups/OpportunityCategoryService.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/Lookups/OpportunityDifficultyService.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/Lookups/OpportunityStatusService.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/Lookups/OpportunityTypeService.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/Lookups/OpportunityVerificationTypeService.cs
- src/api/src/domain/Yoma.Core.Domain/PartnerSharing/Services/Lookups/PartnerService.cs
- src/api/src/domain/Yoma.Core.Domain/PartnerSharing/Services/Lookups/ProcessingStatusService.cs
- src/api/src/domain/Yoma.Core.Domain/Reward/Services/Lookups/RewardTransactionStatusService.cs
- src/api/src/domain/Yoma.Core.Domain/Reward/Services/Lookups/WalletCreationStatusService.cs
- src/api/src/domain/Yoma.Core.Domain/SSI/Services/Lookups/SSICredentialIssuanceStatusService.cs
- src/api/src/domain/Yoma.Core.Domain/SSI/Services/Lookups/SSISchemaEntityService.cs
- src/api/src/domain/Yoma.Core.Domain/SSI/Services/Lookups/SSISchemaTypeService.cs
- src/api/src/domain/Yoma.Core.Domain/SSI/Services/Lookups/SSITenantCreationStatusService.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.AmazonS3/Client/AmazonS3ClientFactory.cs
Update cache keys to use full class names for extensibility and conflict mitigation
> [YOMA-312] Update cache key generation

- helm/keycloak/values.yaml
* Headers are massive for some reason
https://jam.dev/c/426e8a5d-e835-4086-a9c0-3b8504d40770
https://jam.dev/c/4a81784d-2874-49b3-aca8-8d9babb6992a
Closes YOMA-318
> Enable Nginx Ingress Proxy Buffering for Keycloak

- src/api/src/domain/Yoma.Core.Domain/Opportunity/Enumerations.cs
- src/api/src/domain/Yoma.Core.Domain/PartnerSharing/Enumerations.cs
- src/api/src/domain/Yoma.Core.Domain/PartnerSharing/Interfaces/Lookups/IPartnerService.cs
- src/api/src/domain/Yoma.Core.Domain/PartnerSharing/Models/ProcessingLog.cs
- src/api/src/domain/Yoma.Core.Domain/PartnerSharing/Services/Lookups/PartnerService.cs
- src/api/src/domain/Yoma.Core.Domain/PartnerSharing/Services/SharingBackgroundService.cs
- src/api/src/domain/Yoma.Core.Domain/PartnerSharing/Services/SharingService.cs
- src/api/src/domain/Yoma.Core.Domain/SSI/Services/SSITenantService.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/PartnerSharing/Repositories/ProcessingLogRepository.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/Startup.cs
Sharing Service
Sharing Background Service
> [YOMA-309, YOMA-310] Sharing Services

- src/web/src/components/Common/SelectButtons.tsx
- src/web/src/components/Opportunity/FilterTab.tsx
- src/web/src/components/Opportunity/OpportunitiesCarousel.tsx
- src/web/src/components/Opportunity/OpportunityCategoriesHorizontalFilter.tsx
- src/web/src/components/Opportunity/OpportunityCategoryHorizontalCard.tsx
- src/web/src/components/Opportunity/OpportunityFilterVertical.tsx
- src/web/src/components/Opportunity/OpportunityPublicSmall.tsx
- src/web/src/pages/opportunities/[[...query]]/index.tsx
- src/web/src/styles/globals.scss
* Space carousel cards
* Style filter modal
* Add filter tab button on scroll
* Style horizontal filter cards
* Opp carousel mobile spacing
Closes YOMA-326, YOMA-327
> Opportunity filter & carousel style:

- helm/keycloak/values.yaml
> Increase Keycloak Nginx Buffers

- .vscode/extensions.json
- .vscode/settings.json
* Format on Save
* Add Error Lens to recommended extensions
* Add Dependi to recommended extensions
* Sort `.vscode/extensions.json` alphabetically
> VSCode Quality of Life

- src/api/src/application/Yoma.Core.Api/Controllers/MyOpportunityController.cs
- src/api/src/application/Yoma.Core.Api/appsettings.json
- src/api/src/domain/Yoma.Core.Domain/ActionLink/Models/Link.cs
- src/api/src/domain/Yoma.Core.Domain/Analytics/Models/OrganizationOpportunity.cs
- src/api/src/domain/Yoma.Core.Domain/Analytics/Models/OrganizationOpportunitySkill.cs
- src/api/src/domain/Yoma.Core.Domain/Analytics/Models/OrganizationSSO.cs
- src/api/src/domain/Yoma.Core.Domain/Core/Models/TimeIntervalSummary.cs
- src/api/src/domain/Yoma.Core.Domain/Core/Models/TimeValueEntry.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Interfaces/IMyOpportunityService.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Models/MyOpportunitySearchFilterBase.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Models/MyOpportunitySearchFilterSummary.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Models/MyOpportunitySearchResultsSummary.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Services/MyOpportunityService.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Validators/MyOpportunitySearchFilterValidator.cs
> [YOMA-381] Add endpoint for time-based summary search of 'my' opportunities

- src/api/src/application/Yoma.Core.Api/Controllers/MyOpportunityController.cs
- src/api/src/domain/Yoma.Core.Domain/Core/Helpers/FileHelper.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Interfaces/IMyOpportunityService.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Services/MyOpportunityBackgroundService.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Services/MyOpportunityService.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/OpportunityBackgroundService.cs
- src/api/src/domain/Yoma.Core.Domain/Startup.cs
Added endpoint enabling download of verification files, if any, for pending, completed or rejected 'my' opportunities (Authenticated User)
> [YOMA-394] Added endpoint enabling download of verification files

- helm/keycloak/conf/dev/values.yaml
- helm/keycloak/conf/local/values.yaml
- helm/keycloak/conf/prod/values.yaml
- helm/keycloak/conf/stage/values.yaml
- helm/keycloak/values.yaml
* Yoma is a public repo
* Don't need Github PAT to download the tarball
> Remove Github PAT from Keycloak Config CLI

- helm/keycloak/conf/dev/secrets.yaml
- helm/keycloak/conf/local/secrets.yaml
- helm/keycloak/conf/prod/secrets.yaml
- helm/keycloak/conf/stage/secrets.yaml
#965 removed using the Github PAT, but I forgot to remove it from the `secrets.yaml` files
> Clean up unused Github PAT secret

- helm/yoma-api/values.yaml
Another attempt at jumbo headers
> Increase Nginx Proxy Size

- src/web/src/components/YoID/OpportunitiesSummary.tsx
* YoID opportunities summary view colours and graph
Closes YOMA-463
> YoID Opps summary colours

- src/api/src/application/Yoma.Core.Api/Controllers/OrganizationController.cs
- src/api/src/domain/Yoma.Core.Domain/Entity/Services/OrganizationService.cs
- src/api/src/domain/Yoma.Core.Domain/PartnerSharing/Models/OppotunityRequestUpsert.cs
- src/api/src/domain/Yoma.Core.Domain/PartnerSharing/Services/SharingBackgroundService.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/Migrations/20240723103044_ApplicationDb_Settings_Rework_Seeding.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.SAYouth/Client/SAYouthClient.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.SAYouth/Models/OpportunityUpsertResponse.cs
- Organization Create: Logo no longer required
- Organization Update Logo: Allow admins to add or update logo; restrict users to adding only if they are the original creator and the organization is inactive
> [YOMA-466] Organization Logo

- src/web/src/components/YoID/OpportunitiesSummary.tsx
- src/web/src/pages/yoid/index.tsx
Resize opps summary for mobile
> Resize opps summary for mobile

- src/web/src/components/YoID/OpportunitiesSummary.tsx
- src/web/src/pages/yoid/index.tsx
- Refactor component, remove aspect ratio & grid
> Opps summary overflow

- helm/keycloak/values.yaml
- helm/yoma-api/values.yaml
- helm/yoma-web/values.yaml
* `js-lib@5.10.0` -> `js-lib@5.19.0`
* `java-lib@1.33.0` -> `java-lib@1.38.0`
* `dotnet-lib@2.49.0` -> `dotnet-lib@2.56.0`
> Bump Datadog Lib Init

- helm/yoma-api/conf/stage/values.yaml
- src/web/Dockerfile
* Also increase stage yoma api replicas to 2
> Resolve Docker Build warnings

- helm/yoma-api/conf/base/secrets.yaml
- src/api/src/infrastructure/Yoma.Core.Infrastructure.SAYouth/Client/SAYouthClient.cs
Handle 400 response for pause/resume by ignoring error if state is already correct
Prepped initial scheduling population script
> [YOMA-323, YOMA-308] SA Youth Partner Sharing

- src/api/src/domain/Yoma.Core.Domain/Marketplace/Services/StoreAccessControlRuleService.cs
Kept individual rule counts while avoiding over-counting of repeated users
> Calculated UserCountTotal as unique users across all rules

- src/api/src/domain/Yoma.Core.Domain/Marketplace/Services/StoreAccessControlRuleService.cs
> Ensures the rule being edited will not appear in the preview of related rules

- helm/yoma-api/conf/prod/secrets.yaml
* Update Yoma API Helm to use CloudAPI Prod environment
> CloudAPI Prod

- helm/yoma-api/conf/base/secrets.yaml
- src/api/src/application/Yoma.Core.Api/appsettings.json
- src/api/src/domain/Yoma.Core.Domain/Core/Models/AppSettings.cs
- src/api/src/domain/Yoma.Core.Domain/SSI/Services/SSIBackgroundService.cs
Cherry-pick from `hotfix/pause-ssi`
> Add ability to toggle SSI

- helm/yoma-api/conf/prod/secrets.yaml
- src/api/src/application/Yoma.Core.Api/appsettings.json
> CloudAPI UAT

- .github/workflows/cicd.yml
- src/api/Dockerfile
- src/api/src/application/Yoma.Core.Api/Yoma.Core.Api.csproj
- src/api/src/domain/Yoma.Core.Domain/Yoma.Core.Domain.csproj
- src/api/src/infrastructure/Yoam.Core.Infrastructure.Bitly/Yoma.Core.Infrastructure.Bitly.csproj
- src/api/src/infrastructure/Yoma.Core.Infrastructure.AmazonS3/Yoma.Core.Infrastructure.AmazonS3.csproj
- src/api/src/infrastructure/Yoma.Core.Infrastructure.AriesCloud/Yoma.Core.Infrastructure.AriesCloud.csproj
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/Yoma.Core.Infrastructure.Database.csproj
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Emsi/Yoma.Core.Infrastructure.Emsi.csproj
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Keycloak/Yoma.Core.Infrastructure.Keycloak.csproj
- src/api/src/infrastructure/Yoma.Core.Infrastructure.SAYouth/Yoma.Core.Infrastructure.SAYouth.csproj
- src/api/src/infrastructure/Yoma.Core.Infrastructure.SendGrid/Yoma.Core.Infrastructure.SendGrid.csproj
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Shared/Yoma.Core.Infrastructure.Shared.csproj
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Twillio/Yoma.Core.Infrastructure.Twilio.csproj
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Zlto/Yoma.Core.Infrastructure.Zlto.csproj
> [YOMA-617] Upgrade target framework to .NET 9

- src/api/src/domain/Yoma.Core.Domain/Analytics/Models/OrganizationSearchResultsYouth.cs
- src/api/src/domain/Yoma.Core.Domain/Analytics/Models/YouthInfo.cs
- src/api/src/domain/Yoma.Core.Domain/Analytics/Services/AnalyticsService.cs
Updated completed by youth result set to group by youth, include completion count & cumulative rewards, order by completed count desc, and add completed opportunities sub-list
> [YOMA-637] Partner Dash - Completed by Youth

- src/web/src/components/NavBar/UserMenu.tsx
- src/web/src/pages/index.tsx
Add sign out button to UserMenu and align font size on homepage
Closes: YOMA-646, YOMA-650
> Add sign out button to UserMenu and align font size on homepage

- src/web/src/components/NavBar/UserMenu.tsx
Align sign out button to bottom of user menu & add space above
> Align sign out btn to bottom & add space

- helm/keycloak/values.yaml
> Update Datadog APM Injection on Keycloak

- src/api/src/domain/Yoma.Core.Domain/Analytics/Services/AnalyticsService.cs
Top Skills Awarded now ordered by count desc
Engagement Viewed renamed to views
> Cumulative now includes top 10 and 'Rest of Ecosystem)

- src/api/src/domain/Yoma.Core.Domain/Core/Services/DownloadBackgroundService.cs
> Fixed Npgsql.NpgsqlException (0x80004005): Exception while reading from stream

- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Services/MyOpportunityService.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.SendGrid/Client/SendGridClient.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Zlto/Client/ZltoClient.cs
- Implement parallel downloads for verification files
- Enforce 1000-personalizations limit in SendGrid email batching
> Fix: Parallel downloads & SendGrid personalization batching

- helm/yoma-api/conf/base/values.yaml
- helm/yoma-api/conf/dev/values.yaml
- helm/yoma-api/conf/prod/values.yaml
- helm/yoma-api/conf/stage/values.yaml
- helm/yoma-api/values.yaml
* Create empty dir `/data` volume
* Also bump Prod resources
> Yoma API EmptyDir `/data`

- helm/keycloak/conf/prod/values.yaml
- helm/keycloak/values.yaml
* CPU Request 100m -> 250m
* Memory Request/Limit 1.5Gi -> 2Gi
> Increase Keycloak Resources

- src/api/src/domain/Yoma.Core.Domain/SSI/Services/SSIBackgroundService.cs
Fallback to email prefix or cleaned phone number when display name (e.g. هيثم صابر) is empty after removing special characters
> [YOMA-717] SSI Holder Tenant Naming

- helm/yoma-api/conf/base/secrets.yaml
> Increase WhatsApp Delivery Polling Timeout

- src/api/src/application/Yoma.Core.Api/appsettings.json
- src/api/src/domain/Yoma.Core.Domain/ActionLink/Services/LinkService.cs
- src/api/src/domain/Yoma.Core.Domain/Entity/Services/OrganizationService.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Services/MyOpportunityService.cs
- src/api/src/domain/Yoma.Core.Domain/Notification/Constants.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/OpportunityService.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.SendGrid/Client/SendGridClient.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Twillio/Client/TwilioClient.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Twillio/SMSTemplates.Designer.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Twillio/SMSTemplates.resx
- Updated WhatsApp templates to new Meta-compliant versions
- Set default display name to "there" when user name is missing
- Increased WhatsApp delivery polling timeout to 15 seconds
- Aligned SMS fallback logic and templates with WhatsApp delivery checks
> [YOMA-798] Notification template updates

- helm/keycloak/conf/prod/values.yaml
* Make it so that Prod Keycloak may not share hosts
* Prod Keycloak must be multi-AZ
> Prod Keycloak Hard Anti-Affinity

- src/api/src/domain/Yoma.Core.Domain/SSI/Enumerations.cs
- src/api/src/domain/Yoma.Core.Domain/SSI/Models/SSISchema.cs
- src/api/src/domain/Yoma.Core.Domain/SSI/Services/SSIBackgroundService.cs
- src/api/src/domain/Yoma.Core.Domain/SSI/Services/SSISchemaService.cs
- src/api/src/domain/Yoma.Core.Domain/Yoma.Core.Domain.csproj
- src/api/src/infrastructure/Yoma.Core.Infrastructure.AriesCloud/Client/AriesCloudClient.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.AriesCloud/Extensions/SchemaExtensions.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/Migrations/20250715070701_ApplicationDb_UpdateArtifactType_AnonCredsToACR.Designer.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/Migrations/20250715070701_ApplicationDb_UpdateArtifactType_AnonCredsToACR.cs
- src/api/src/test/Yoma.Core.Test/Yoma.Core.Test.csproj
> [YOMA-849] chore: rename ArtifactType enum from AnonCreds to ACR and update DB CredentialIssuance table

- helm/yoma-web/conf/stage/values.yaml
This reverts commit 0afe1cb786a9c8985efe658b80234d16544b3db0.
> Revert "Disable Yoma Passport in Stage (#1427)"

- src/api/src/domain/Yoma.Core.Domain/Core/Enumerations.cs
- src/api/src/domain/Yoma.Core.Domain/Core/Services/DownloadBackgroundService.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/OpportunityInfoService.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/Migrations/20250814120922_ApplicationDb_UpdateDownloadScheduleType_OpporunitiesToOpportunities.Designer.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/Migrations/20250814120922_ApplicationDb_UpdateDownloadScheduleType_OpporunitiesToOpportunities.cs
- Updated Download.Schedule table to correct typo in Type column
- Added Down migration to revert the change if needed
> chore(migrations): rename DownloadScheduleType 'Opporunities' to 'Opportunities

- helmfile.yaml.gotmpl
https://github.com/bitnami/containers/issues/84600
> Migrate `docker.io/bitnami` -> `docker.io/bitnamilegacy`
