- src/api/src/application/Yoma.Core.Api/Attributes/ApiKeyAttribute.cs
- src/api/src/application/Yoma.Core.Api/Controllers/ExternalPartnerController.cs
- src/api/src/domain/Yoma.Core.Domain/Entity/Interfaces/IOrganizationService.cs
- src/api/src/domain/Yoma.Core.Domain/Entity/Services/OrganizationService.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Enumerations.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/OpportunityService.cs
Remove GetByApiKey method from organization service Require active associated organization for creating and updating opportunities
> Hide external partner controller for future use

- src/web/next.config.mjs
prevents the downloading all assets on first site visit
> disable prefetching of all assets (next-pwa service worker)

- .gitattributes
Force all text files to `\n` on end of line.
Should, hopefully, mean no more worrying about DOS `\r\n` and *nix `\n` clashes anymore.
> Set End-Of-Line to `lf`

- src/api/src/domain/Yoma.Core.Domain/Entity/Services/UserService.cs
- src/api/src/domain/Yoma.Core.Domain/Lookups/Interfaces/ISkillService.cs
- src/api/src/domain/Yoma.Core.Domain/Lookups/Services/SkillService.cs
- src/api/src/domain/Yoma.Core.Domain/Startup.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/Entity/Repositories/UserRepository.cs
Implemented logic to ensure skill seeding occurs only during the initial startup, preventing re-seeding on subsequent restarts Resolved an issue where DateYoIDOnboarded was not being correctly assigned
> Successfully tested EMSI skill seeding using updated credentials

- .github/workflows/cicd.yml
Because, obviously, we want to deploy things to prod when we do a release
> [YOMA-16] Fix missing `Should deploy` check for `release`

- helm/yoma-api/templates/deployment.yaml
- src/api/src/application/Yoma.Core.Api/Startup.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/Startup.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/Yoma.Core.Infrastructure.Database.csproj
Enable anonymous access to these endpoints to allow health monitoring by external systems without authentication Utilize default ASP.NET Core Health Checks behavior to return HTTP 200 for Healthy and HTTP 503 for Unhealthy or Degraded states, facilitating straightforward integration with load balancers and monitoring tools
> Set up basic and detailed health checks at /api/v3/health/ready and /api/v3/health/live

- helm/yoma-web/conf/base/secrets.yaml
- helm/yoma-web/conf/dev/secrets.yaml
- helm/yoma-web/conf/prod/secrets.yaml
- helm/yoma-web/conf/stage/secrets.yaml
- src/keycloak/exports/01-yoma-realm.yaml
Partially reverts #698 
---
* Goodwall and Atingi clients don't need Direct Access Grants or Service
Accounts
* Yoma Web is no longer using Goodwall/Atingi clients as auth providers,
so remove Yoma Web URL from them
> Partial revert of #698

- helm/yoma-web/conf/dev/values.yaml
- helm/yoma-web/conf/prod/values.yaml
- helm/yoma-web/conf/stage/values.yaml
* Increase default `large_client_header_buffers 4 8k` to `8 32k`
* Nginx [`large_client_header_buffers`](https://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers)
* Ingress Nginx [`large-client-header-buffers`](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#large-client-header-buffers)
* Enable Proxy Buffering
* [nginx.ingress.kubernetes.io/proxy-buffering](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#proxy-buffering)
* Increase Number of Proxy Buffers from `4` to `8`
* [nginx.ingress.kubernetes.io/proxy-buffers-number](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#proxy-buffers-number)
---
> Syntax: large_client_header_buffers number size;
> …
> Increase Nginx Proxy Buffer for Yoma Web Ingresses

- .github/workflows/cicd.yml
`vars.ENVIRONMENT` wasn't resolving because it's an environment
(dev|stage|prod) specific variable and it's not resolvable when the
concurrency group is being set
> Hotfix: Fix Deploy Concurrency Group

- src/keycloak/exports/01-yoma-realm.yaml
* Hash Algo `pbkdf2-sha256` -> `pbkdf2-sha512`
* Hash Iterations `27,500` -> `250,000`
* Minimum 10 characters
* Minimum 1 lower case
* Minimum 1 upper case
* Minimum 1 number
* No special characters needed
* Not username
* Not email
https://www.keycloak.org/docs/latest/server_admin/index.html#_password-policies
---
* Enable Brute Force detection
https://www.keycloak.org/docs/latest/server_admin/index.html#password-guess-brute-force-attacks
> Keycloak Password Policy

- .github/workflows/cicd.yml
* Helmfile and Helm versions weren't pinned in Deploy Fresh DBs step
* Helmfile `1.0.0-rc1` has breaking changes which causes our helmfile to break
> Fix deploy fresh dbs

- src/api/src/domain/Yoma.Core.Domain/ActionLink/Validators/LinkRequestCreateValidatorVerify.cs
- src/api/src/domain/Yoma.Core.Domain/Analytics/Services/AnalyticsService.cs
Update average conversion rate calculation to reflect viewed/completed counts from filtered engagement
> Allow link end date set to today as valid if created before midnight UTC

- helm/keycloak/conf/dev/values.yaml
- helm/keycloak/conf/local/values.yaml
- helm/keycloak/conf/prod/values.yaml
- helm/keycloak/conf/stage/values.yaml
- helm/keycloak/values.yaml
- helm/yoma-api/conf/prod/secrets.yaml
- helm/yoma-api/conf/prod/values.yaml
- helm/yoma-web/conf/prod/secrets.yaml
- helm/yoma-web/conf/prod/values.yaml
* Drop the `app` subdomain from Yoma Web
* Migrate `auth.yoma.world` to `yoma.world/auth`
Relates to #733
> [YOMA-15] Migrate Yoma Web to `yoma.world`

- helm/keycloak/conf/prod/values.yaml
- helm/keycloak/values.yaml
- helm/yoma-api/conf/prod/values.yaml
- helm/yoma-web/conf/prod/values.yaml
- helm/yoma-web/values.yaml
* Yoma Web
* By default, request 50mvCPU, 128Mi Memory
* Prod, double it - 100mvCPU request and 500mvCPU limit. 256Mi Memory Req/Limit
* Yoma API
* Increase CPU Limit from 2vCPU to 2.5vCPU
* Keycloak
* Increase Memory from 1Gi to 1.5Gi
* Increase CPU Request to 100mvCPU
* Increase CPU Limit to 4vCPU
* Increase JVM Max RAM Percentage from 50% to 75%
* Use Helm Templating to calculate `-Xmx` value based of `resources.limits.memory`
* According to GPT, specifying both `-XX:MaxRAMPercentage` and `-Xmx`, the JVM will use whichever is the _lower_ value
> Increase Resource Requests and Limits

- helm/yoma-web/conf/prod/values.yaml
- helm/yoma-web/values.yaml
* Yoma Web in Stage was memory starved causing pods to crash when trying
to log in
> Bump Yoma Web Memory Request/Limits

- helm/keycloak/conf/dev/values.yaml
- helm/keycloak/conf/stage/values.yaml
- helm/keycloak/values.yaml
- helm/yoma-web/conf/prod/values.yaml
- helm/yoma-web/values.yaml
* Bump Yoma Web Memory from 256Mi to 386Mi
* Bump Keycloak Memory from 512Mi to 768Mi, increase CPU from 50m to 100m request
---
Relates to YOMA-176
> Bump Yoma Web and Keycloak resources

- src/api/src/domain/Yoma.Core.Domain/Lookups/Helpers/TimeIntervalHelper.cs
- src/api/src/domain/Yoma.Core.Domain/Lookups/Services/TimeIntervalService.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/OpportunityService.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/Migrations/20240522063953_ApplicationDb_Featured_Types_Intervals_Seeding.cs
Added custom ordering for TimeInterval based on interval duration. Ordered with the least interval first: Minutes, Hours, Days, Weeks, Months
Opportunity end date validation: Today is now included. So if the duration based on the commitment interval is 1, the opportunity can start end end on the same day
> Time interval ordering and opportunity end date validation

- src/api/src/application/Yoma.Core.Api/Controllers/OrganizationController.cs
- src/api/src/domain/Yoma.Core.Domain/Analytics/Interfaces/IAnalyticsService.cs
- src/api/src/domain/Yoma.Core.Domain/Analytics/Interfaces/IOrganizationSearchFilterBase.cs
- src/api/src/domain/Yoma.Core.Domain/Analytics/Interfaces/IOrganizationSearchFilterEngagement.cs
- src/api/src/domain/Yoma.Core.Domain/Analytics/Models/OrganizationSearchFilterBase.cs
- src/api/src/domain/Yoma.Core.Domain/Analytics/Models/OrganizationSearchFilterEngagement.cs
- src/api/src/domain/Yoma.Core.Domain/Analytics/Models/OrganizationSearchFilterYouth.cs
- src/api/src/domain/Yoma.Core.Domain/Analytics/Services/AnalyticsService.cs
- src/api/src/domain/Yoma.Core.Domain/Analytics/Validators/OrganizationSearchFilterEngagementValidator.cs
- src/api/src/domain/Yoma.Core.Domain/Analytics/Validators/OrganizationSearchFilterValidatorBase.cs
- src/api/src/domain/Yoma.Core.Domain/Analytics/Validators/OrganizationSearchFilterYouthValidator.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Models/MyOpportunity.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/MyOpportunity/Repositories/MyOpportunityRepository.cs
Added endpoint to get a list of countries associated with users that engaged with opportunities (viewed and / or completed)
Country filtering now only applies to engagement (old engagement and completed youth)
> [YOMA-227] User countries that engaged with opportunities

- .github/workflows/cicd.yml
During the release to Vercel it was noted that Lint doesn't support Release actions.
So I've added a condition to the Lint step that will skip it if it's a github release.
https://github.com/didx-xyz/yoma/actions/runs/9462473678/job/26065520951
```
Error: lint-action does not support "release" GitHub events
```
---
* Tailscale `1.64.0` -> `1.68.0`
* Helmfile `0.163.1` -> `0.165.0`
* Helm `3.14.4` -> `3.15.2`
> Bump Deploy dependencies, don't lint on release

- .github/workflows/cicd.yml
- helm/keycloak/Chart.lock
- helm/keycloak/Chart.yaml
- helm/keycloak/values.yaml
- helm/yoma-api/Chart.lock
- helm/yoma-api/Chart.yaml
- helm/yoma-api/conf/prod/values.yaml
- helm/yoma-api/conf/stage/values.yaml
- helm/yoma-api/templates/_helpers.tpl
- helm/yoma-api/templates/deployment.yaml
- helm/yoma-api/templates/hpa.yaml
- helm/yoma-api/templates/ingress.yaml
- helm/yoma-api/templates/pdb.yaml
- helm/yoma-api/templates/post-install.yaml
- helm/yoma-api/templates/pvc.yaml
- helm/yoma-api/templates/secret.yaml
- helm/yoma-api/templates/service.yaml
- helm/yoma-api/templates/serviceaccount.yaml
- helm/yoma-api/values.yaml
* Enable Horizontal Pod Autoscaling of Yoma API
* If CPU usage exceeds 200% of the **_request_**, begin scaling pods
* Enable Pod Disruption Budgets for Yoma API to guarantee pod uptime
* Add a 5s sleep pre-stop lifecycle hook
* Use Bitnami pattern for health probes
* Add `bitnami/common` as a dependency to Yoma API
* Configure HPA Behavior
* Use Bitnami's Affinity templating
> Yoma API HPA, PDB, Pre-Stop, better health probes

- package.json
* Fix `install command is DEPRECATED` warning
> Fix Husky Install Deprecated warning

- src/api/src/infrastructure/Yoma.Core.Infrastructure.SAYouth/Client/SAYouthClient.cs
Ensure 'FaceToFace' is set to 'No' so the YOMA link always shows on SA Youth; resulting in no contact and address info being posted; opportunity will always be listed as 'Online Opportunity'
> SA Youth: Always flagged as non face-to-face

- helm/keycloak/Chart.lock
- helm/keycloak/values.yaml
- helm/yoma-api/Chart.lock
- helm/yoma-api/values.yaml
- helm/yoma-web/values.yaml
* Bump `bitnami/common` `2.22.0` -> `2.23.0`
* Bump Datadog Java Lib `1.38.1` -> `1.39.0`
* Bump Datadog Dotnet Lib `2.57.0` -> `3.3.0`
* Bump Datadog JS Lib `5.19.0` -> `5.22.0`
> Bump Helm dependencies

- src/api/src/domain/Yoma.Core.Domain/Marketplace/Models/StoreAccessControlRuleEvaluationItemReason.cs
- src/api/src/domain/Yoma.Core.Domain/Marketplace/Models/StoreAccessControlRuleEvaluationItemReasonLink.cs
- src/api/src/domain/Yoma.Core.Domain/Marketplace/Services/StoreAccessControlRuleService.cs
- Implemented `ConditionPassed` to report if a rule's condition (age, gender, opportunities) was satisfied.
- Introduced `RequirementMet` in opportunity links to indicate whether the user completed each opportunity.
> Added flags for condition and link evaluation in rule processing

- src/api/src/domain/Yoma.Core.Domain/Marketplace/Services/StoreAccessControlRuleService.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.SAYouth/Client/SAYouthClient.cs
- SA Youth: ensure 'HasCertification' of type 'NonAccreditedCertification' when 'VerificationEnabled'; Yoma's certification is not accredited
- Access Rules: Fixed issue with completed opportunity comparisons
> [YOMA-528, YOMA-482] Access Rules and SA Youth bug fixes

- helm/keycloak/conf/dev/secrets.yaml
- helm/keycloak/conf/prod/secrets.yaml
- helm/keycloak/conf/stage/secrets.yaml
- helm/keycloak/values.yaml
- src/api/docker-compose.yml
* Using the Twilio Test keys in Dev and Stage
* Using Twilio Test number in Dev
* Stage and Prod have a placeholder while we wait for the actual Yoma number
* Twilio Live credentials in Prod
* Download our custom Twilio Provider JARs in the Download Providers init container
> YOMA-538: Configure Twilio Keycloak SMS Provider

- helm/keycloak/conf/prod/values.yaml
> Hotfix: Keycloak Memory Req/Limits

- src/api/src/infrastructure/Yoma.Core.Infrastructure.Keycloak/Client/KeycloakClient.cs
- src/keycloak/exports/02-yoma-profile.yaml
Fix Keycloak user profile: 'terms_and_conditions' not required for admins but editable
> Assign default 'User' role to users created via B2B endpoint

- .github/workflows/cicd.yml
- helm/keycloak/conf/dev/secrets.yaml
- helm/yoma-api/conf/base/secrets.yaml
- helm/yoma-api/conf/dev/values.yaml
- helmfile.yaml.gotmpl
- src/api/docker-compose.yml
* On a fresh deployment of Yoma API, we only want a single replica due
to DB migrations
* If multiple replicas are started up on a fresh deploy, one of them
will error and hang indefinitely (until startup probe restarts it)
* Make Helm Plugins an environment variable to deduplicate and make
things a bit more maintainable
> Single Yoma API replica on fresh deployment

- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/OpportunityBackgroundService.cs
- src/api/src/other/Completions (Submissions) CSV Import — README.txt
- src/api/src/other/Opportunities CSV Import — README.txt
- Refined Opportunities and Completions CSV import README files for clarity, completeness, and tester alignment
- Explicitly stated SEO/search purpose of Keywords in Opportunities README
- Updated Custom GPT runtime behavior section (no validation report downloads, phantom row handling, simplified outputs)
- Adjusted auto-deletion logic per customer request: • Excluded Inactive opportunities from auto-deletion • Only Expired opportunities will be auto-deleted after 180 days • Added explanatory code comment documenting this change
> chore: update CSV import READMEs and adjust auto-deletion rule

- src/api/src/application/Yoma.Core.Api/Controllers/OpportunityController.cs
- src/api/src/domain/Yoma.Core.Domain/Core/Extensions/EnumExtensions.cs
- src/api/src/domain/Yoma.Core.Domain/Entity/Services/OrganizationService.cs
- src/api/src/domain/Yoma.Core.Domain/Marketplace/Services/StoreAccessControlRuleService.cs
- src/api/src/domain/Yoma.Core.Domain/MyOpportunity/Services/MyOpportunityService.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Enumerations.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Events/OpportunityEventHandler.cs
- src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/OpportunityService.cs
- src/api/src/domain/Yoma.Core.Domain/PartnerSharing/Services/SharingBackgroundService.cs
- src/api/src/domain/Yoma.Core.Domain/Startup.cs
- src/api/src/infrastructure/Yoma.Core.Infrastructure.SAYouth/Client/SAYouthClient.cs
- Prevent auto-deletion of Inactive opportunities (manual handling only).
- Auto-delete Expired opportunities after 180 days (6 months).
- Keep Expired opportunities visible to youth for completion/upload during grace period.
- Cosmetically rename status Deleted -> Archived across buttons, headers, labels, and validation messages.
> [YOMA-942] Update opportunity status handling

- helm/keycloak/Chart.lock
- helm/keycloak/Chart.yaml
- helm/yoma-api/Chart.lock
- helm/yoma-api/Chart.yaml
- helmfile.yaml.gotmpl
Migrate Helm chart dependencies from public Bitnami registry to
DIDx-maintained fork at `ghcr.io/didx-xyz/bitnami-oss-charts` for
continued maintenance.
Key changes:
* Update Chart.yaml dependencies to point to DIDx registry
* Regenerate Chart.lock files with new versions and digests
* Switch PostgreSQL image from `bitnamilegacy` to DIDx registry
* Update Valkey chart and all related image repositories
* Add imageRegistry configuration for custom registry support
* Upgrade common chart dependency from 2.23.0 to 2.31.4
* Update documentation references to DIDx repository
This ensures consistency across all components while maintaining
compatibility with existing configurations.
> Update Helm charts to use DIDx registry
